databases:
  - name: myrubyshop
    databaseName: myrubyshop
    user: myrubyshop
    plan: free

services:
  - type: web
    name: myrubyshop
    runtime: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    # preDeployCommand: "bundle exec rails db:migrate" # preDeployCommand only available on paid instance types
    startCommand: "bundle exec rails server"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: myrubyshop
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2 # sensible default
      - key: USER_EMAIL
        value: "dothanhdoan@gmail.com" 
      - key: USER_PASSWORD
        value: "dothanhdoan" 